# Generated by Django 2.2.4 on 2020-08-20 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fav_app', '0001_initial'),
        ('log_reg_app', '0003_auto_20200818_1938'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
